function session_info = make_session_database;
% Make database entires for experiments so we can integrate and exchange
% data
clear session_info

si = 0;


si = si+1;
session_info(si).date = '03apr09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = nan; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = nan;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1807';
session_info(si).include = 1;


si = si+1;
session_info(si).date = '07apr09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'MeA'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.65; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.65;
session_info(si).Z = 5.5;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1807';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '10apr09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 24;
session_info(si).ML = 2; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.65;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1807';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '14apr09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 24;
session_info(si).ML = 1.63; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.65;
session_info(si).Z = 5.6;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1807';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '15may09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.9; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.7;
session_info(si).Z = 5.98;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1807';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '15may09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.65; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.95;
session_info(si).Z = 5.98;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '20may09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.8; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.7;
session_info(si).Z = 5.78;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '04jun09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'MeA-PMCO'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 16;
session_info(si).ML = 1.65; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.6;
session_info(si).Z = 5.52;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '915';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '11jun09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.8; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.6;
session_info(si).Z = 5.5;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '915';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '18jun09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'PMCO'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 2; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.95;
session_info(si).Z = 5.9;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '23jun09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 2; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.95;
session_info(si).Z = 6;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '30jun09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'too medial'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.75; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.6;
session_info(si).Z = 6;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '915';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '30jun09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'MeA'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.95; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.6;
session_info(si).Z = 6;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '915';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '08jul09';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NA'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 14;
session_info(si).ML = 1.7; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.6;
session_info(si).Z = 5.43;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '915';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '15jul09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'F';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.85; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.6+0.3;
session_info(si).Z = 5.83;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '915';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '15jul09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'F';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 2; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.6+0.3;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '915';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '15jul09';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'F';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 2.2; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 2.3+0.25;
session_info(si).Z = 6;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '20aug09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO-PLCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'PMCO'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 2.6; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 2.2+0.25;
session_info(si).Z = 5.3;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '20aug09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO-PLCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 2; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.8+0.25;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '01sep09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.75; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.3+0.3;
session_info(si).Z = 5.7;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '915';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '01sep09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 2; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.7+0.25;
session_info(si).Z = 5.8;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '02sep09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'MeA','Pyr'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).ML = 1.7; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.7-0.25;
session_info(si).Z = 6.3;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '04sep09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).ML = 1.7; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.7-0.25;
session_info(si).Z = 6.5;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '04sep09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).ML = 1.9; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.6-0.25;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '04sep09';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO-PLCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).ML = 2.3; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 2-0.25;
session_info(si).Z = 6.3;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '08sep09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'PLCO','PLCO-MePD'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).ML = 1.7; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.7+0.25;
session_info(si).Z = 6.5;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09sep09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA-PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'MeA','PMCO'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).ML = 1.8; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.6+0.25;
session_info(si).Z = 6.2;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1486';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09sep09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA-PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'PMCO-MeA','PMCO'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).ML = 1.7; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.7+0.25;
session_info(si).Z  = 6;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '29sep09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA-PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NA'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.6; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.7+0.25;
session_info(si).Z  = 6.4;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '01oct09';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA-PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NA'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.6; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.7+0.25;
session_info(si).Z  = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '01oct09';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_integration';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA-PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NA'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = nan;
session_info(si).ML = 1.8; % these coordinates are a guess - we did not write them down on the actual experiment
session_info(si).AP = 1.85+0.25;
session_info(si).Z  = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%





%%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09mar10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA','MeA'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).most_likely_actual_goal = {'NC','NC'}; % NC for not certain, miss for a miss, or give the actual place the electrodes were
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 20;
session_info(si).ML = 1.6;
session_info(si).AP = 1.7;
session_info(si).Z = 6.3;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes counter-clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09mar10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_vns_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA','MeA'}; 
session_info(si).most_likely_actual_goal = {'NC','NC'};
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 20;
session_info(si).ML = 1.8;
session_info(si).AP = 1.8;
session_info(si).Z = 6.3;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '11mar10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_VNS_quicklook';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA','MeA'}; 
session_info(si).most_likely_actual_goal = {'PLCO','PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 20;
session_info(si).AP = 1.7;
session_info(si).ML = 1.6;
session_info(si).Z = 6.15;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '11mar10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_VNS_quicklook','amygdala_vns_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA','MeA'}; 
session_info(si).most_likely_actual_goal = {'PLCO','PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 20;
session_info(si).AP = 1.7;
session_info(si).ML = 1.8;
session_info(si).Z = 6.1;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '11mar10';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_VNS_quicklook','amygdala_vns_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA','MeA'}; 
session_info(si).most_likely_actual_goal = {'PMCO','MeA/PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 20;
session_info(si).AP = 1.7;
session_info(si).ML = 1.4;
session_info(si).Z = 6.1;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '1773';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '18mar10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA','MeA'}; 
session_info(si).most_likely_actual_goal = {'MeA','miss-medial'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 20;
session_info(si).AP = 1.75;
session_info(si).ML = 1.6;
session_info(si).Z = 5.8;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '18mar10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MeA','miss'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 20;
session_info(si).AP = 1.65;
session_info(si).ML = 1.47;
session_info(si).Z = 6.1;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '18mar10';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MeA','miss-medial'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 20;
session_info(si).AP = 1.67;
session_info(si).ML = 1.8;
session_info(si).Z = 5.8;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '23mar10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'PMCO','PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 18;
session_info(si).AP = 1.7;
session_info(si).ML = 1.7;
session_info(si).Z = 6.0;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '23mar10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_vns_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'PMCO','PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 18;
session_info(si).AP = 1.7;
session_info(si).ML = 1.92;
session_info(si).Z = 5.9;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '23mar10';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_vns_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'PMCO','PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 18;
session_info(si).AP = 1.7;
session_info(si).ML = 1.55;
session_info(si).Z = 5.97;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '01apr10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_mos_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MePD','PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.6;
session_info(si).ML = 1.9;
session_info(si).Z = 6.4;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '05apr10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_mos_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MePV/PMCO/MePD','PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.5;
session_info(si).ML = 1.9;
session_info(si).Z = 6.7;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '08apr10';
session_info(si).site = 4;
session_info(si).experiment_type = 'amygdala_vns_mos_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MeA','miss-medial'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.8;
session_info(si).ML = 1.8;
session_info(si).Z = 6.5;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09apr10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_VNS_quicklook';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2.25;
session_info(si).ML = 2.23;
session_info(si).Z = 6;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09apr10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_VNS_quicklook';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'NC'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2.3;
session_info(si).ML = 2;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09apr10';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_VNS_quicklook';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'NC'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2.3;
session_info(si).ML = 2.4;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09apr10';
session_info(si).site = 4;
session_info(si).experiment_type = 'amygdala_VNS_quicklook';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'NC'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2.1;
session_info(si).ML = 1.855;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09apr10';
session_info(si).site = 5;
session_info(si).experiment_type = 'amygdala_VNS_quicklook';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'NC'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2;
session_info(si).ML = 2.3;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '09apr10';
session_info(si).site = 6;
session_info(si).experiment_type = 'amygdala_VNS_quicklook';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'NC'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.7;
session_info(si).ML = 1.7;
session_info(si).Z = nan;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '14apr10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_mos_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO'}; 
session_info(si).most_likely_actual_goal = {'miss-medial,miss-caudal'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2.1;
session_info(si).ML = 2.1;
session_info(si).Z = 5.8;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '14apr10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_vns_mos_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO'}; 
session_info(si).most_likely_actual_goal = {'miss-medial,miss-caudal'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2.18;
session_info(si).ML = 2.35;
session_info(si).Z = 5.8;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '14apr10';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_vns_mos_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO'}; 
session_info(si).most_likely_actual_goal = {'miss-medial,miss-caudal'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2.18;
session_info(si).ML = 2.55;
session_info(si).Z = 5.8;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '14apr10';
session_info(si).site = 4;
session_info(si).experiment_type = 'amygdala_vns_mos_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'PMCO'}; 
session_info(si).most_likely_actual_goal = {'miss-medial,miss-caudal','PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2.18;
session_info(si).ML = 2.7;
session_info(si).Z = 5.8;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = -90; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '16apr10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'miss-medial','MeA',}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1;
session_info(si).ML = 1.6;
session_info(si).Z = 6.5;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '22apr10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MeA',}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1;
session_info(si).ML = 1.6;
session_info(si).Z = 6.3;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '495';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '22apr10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MeA',}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.2;
session_info(si).ML = 1.65;
session_info(si).Z = 6.2;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '584';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '23apr10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'NC','MeA',}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.7;
session_info(si).ML = 1.7;
session_info(si).Z = 6.4;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '584';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '23apr10';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'miss-medial','MEA',}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.9;
session_info(si).ML = 2;
session_info(si).Z = 6.5;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '584';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '23apr10';
session_info(si).site = 4;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MeA','MeA',}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.6;
session_info(si).ML = 1.6;
session_info(si).Z = 5.8;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '584';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '30apr10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'NA',}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.4;
session_info(si).ML = 1.6;
session_info(si).Z = 6.2;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '584';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '30apr10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'NA',}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 2;
session_info(si).ML = 1.5;
session_info(si).Z = 6.2;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '584';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '30apr10';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_vns_mos';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'NA',}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.67;
session_info(si).ML = 1.4;
session_info(si).Z = 6.3;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '584';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '22jul10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_conspecific';
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MePV','MePD-PMCO-PLCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 10;
session_info(si).AP = 1.8;
session_info(si).ML = 1.85;
session_info(si).Z = 6;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '584';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '03aug10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_conspecific+'; % The + refers to having pup and ringers as well
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MePD-MePV','PMCO-MePV'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).AP = 1.7;
session_info(si).ML = 1.8;
session_info(si).Z = 6.2;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = 'CB4';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '03aug10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_vns_conspecific+'; % The + refers to having pup and ringers as well
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MePD-MePV','PMCO-MePV'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).AP = 1.66;
session_info(si).ML = 1.6;
session_info(si).Z = 6.4;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = 'CB4';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '03aug10';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_vns_conspecific+'; % The + refers to having pup and ringers as well
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'MePD-MePV','PMCO-MePV'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).AP = 1.8;
session_info(si).ML = 2.0;
session_info(si).Z = 6.14;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = 'CB4';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '05aug10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_conspecific+'; % The + refers to having pup and ringers as well
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'PMCO','PMCO'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 12;
session_info(si).AP = 1.8;
session_info(si).ML = 1.9;
session_info(si).Z = 6.25;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = '587';
session_info(si).include = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '10aug10';
session_info(si).site = 1;
session_info(si).experiment_type = 'amygdala_vns_conspecific+'; % The + refers to having pup and ringers as well
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'not done yet'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 13;
session_info(si).AP = 1.94;
session_info(si).ML = 2.0;
session_info(si).Z = 6.47;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = 'CB4';
session_info(si).include = 0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '10aug10';
session_info(si).site = 2;
session_info(si).experiment_type = 'amygdala_vns_conspecific+'; % The + refers to having pup and ringers as well
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'not done yet'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 13;
session_info(si).AP = 1.94;
session_info(si).ML = 1.6;
session_info(si).Z = 6.17;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = 'CB4';
session_info(si).include = 0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%
si = si+1;
session_info(si).date = '10aug10';
session_info(si).site = 3;
session_info(si).experiment_type = 'amygdala_vns_conspecific+'; % The + refers to having pup and ringers as well
session_info(si).experimenter = 'yoram';
session_info(si).target_goal = {'MeA'}; 
session_info(si).most_likely_actual_goal = {'not done yet'}; % The first entry is for the more medial (0 angle) or the more rostral (90 angle) shank
session_info(si).mouse_sex  = 'M';
session_info(si).mouse_estrus_stage  = 'NA';
session_info(si).mouse_strain  = 'BalbC';
session_info(si).mouse_age_weeks  = 13;
session_info(si).AP = 1.94;
session_info(si).ML = 2.2;
session_info(si).Z = 6.43;
session_info(si).coordinate_location = 'probe center';
session_info(si).probe_angle         = 0; % Zero when looking at two conducting shank faces - angle changes clockwise with probe
session_info(si).probe = 'CB4';
session_info(si).include = 0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%



% APPEND SPIKE SORTING DATA
% read the spike sorting data
[NUMERIC,TXT]=xlsread(['C:\DATA\cell_database.xlsx']);
headers = TXT(1,:);
datecol = strmatch('date',headers);
sessioncol = strmatch('session',headers);
unitcol = strmatch('unit',headers);
gradecol = strmatch('Nunits',headers);
shapecol = strmatch('shape',headers);
activecol = strmatch('active',headers);

unitDB_dates = TXT(2:end,datecol);
unitDB_sessions = NUMERIC(1:end,1);
unitDB_units    = NUMERIC(1:end,2);
unitDB_grades = TXT(2:end,gradecol);
unitDB_shapes = TXT(2:end,shapecol);
unitDB_stability = TXT(2:end,activecol);

% and change the date format
for i = 1:length(unitDB_dates)
    unitDB_dates{i} = lower(datestr(unitDB_dates{i},'ddmmmyy'));
end

for si = 1:length(session_info)
    rel_columns = intersect(strmatch(session_info(si).date,unitDB_dates),find(session_info(si).site == unitDB_sessions));
    if isempty(rel_columns)
        disp(['no units found for ' session_info(si).date ' session ' num2str( session_info(si).site)]);
    else
        session_info(si).unit_names =   unitDB_units(rel_columns);
        session_info(si).unit_grades =   unitDB_grades(rel_columns);
        session_info(si).unit_shapes =   unitDB_shapes(rel_columns);        
        session_info(si).unit_stability =   unitDB_stability(rel_columns);
    end
end

%%%now get the probe info
for si=1:length(session_info)
    probe_info=get_probe_info(session_info(si).probe);
    
    %session_info(si).groups         =   probe_info.groups;  
    %session_info(si).do_groups      =   probe_info.do_groups;
    session_info(si).probe_type     =   probe_info.type;
    session_info(si).z_spacing      =   probe_info.z_spacing;
    session_info(si).hor_sep        =   probe_info.hor_sep;
    session_info(si).shanks         =   probe_info.shanks;
end

save('c:\data\session_info','session_info');

return


