function divide_combined_cluster_files(combined_datadir,datadir,groups,do_groups,blocks,IBI,SR)
% Split cluster files, after they have been generated by Klustakwik and
% then refined by Klusters into individual files for use by Neuroscope. 


eval(['load ' combined_datadir 'Nspikes']);

for group_ind = 1:length(do_groups)
    disp(['  splitting combined Klusters feature file for group ' groups(do_groups(group_ind)).name] )

    comb_cluster_file_name = [combined_datadir  'group' groups(do_groups(group_ind)).name filesep 'combined' groups(do_groups(group_ind)).name  '.clu.1'];
    comb_times_file_name = [combined_datadir  'group' groups(do_groups(group_ind)).name filesep 'combined' groups(do_groups(group_ind)).name  '.res.1'];  
    xml_file_name          = [combined_datadir  'group' groups(do_groups(group_ind)).name filesep 'combined' groups(do_groups(group_ind)).name '.xml'];
    %comb_cluster_file_name = [combined_datadir 'combined' groups(do_groups(group_ind)) filesep groups(do_groups(group_ind)).name '.clu.1'];           
    fid = fopen(comb_cluster_file_name);
    comb_clusters = fscanf(fid,'%f');
    fclose(fid);
    if ~(sum(Nspikes(do_groups(group_ind),:)) + 1 == length(comb_clusters))
        disp('error in number of spikes')
    end
    
%     fid = fopen(comb_times_file_name);
%     comb_times = fscanf(fid,'%f');
%     fclose(fid);
%     if ~(sum(Nspikes(do_groups(group_ind),:)) == length(comb_times))
%         disp('error in number of spikes')
%     end
    
    blocks_starts = [1 cumsum(Nspikes(do_groups(group_ind),1:end-1))+1];
    blocks_ends = [cumsum(Nspikes(do_groups(group_ind),:))];
    seg_inds = 1 + [blocks_starts' blocks_ends']; % The 1 is added for the cluster designation at the begining
    Nclusts = comb_clusters(1);
    for block_ind = 1:length(blocks)                
        
        block_cluster_file_name = [datadir 'Block-' num2str(blocks(block_ind)) filesep 'Block-' num2str(blocks(block_ind)) '_group' num2str(do_groups(group_ind)) '.clu.1'];
       
        fid = fopen(block_cluster_file_name,'w');
        theseclusters = comb_clusters([seg_inds(block_ind,1):seg_inds(block_ind,2)]);
        theseclusters = [Nclusts theseclusters'];
        fprintf(fid,'%2.0f \n',theseclusters);
        fclose(fid);
        
        %fid = fopen(block_times_file_name,'w');
        % The 1 is subtracted because for the res file, there is no initial
        % value of number of clusters
%         thesetimes = comb_times([seg_inds(block_ind,1):seg_inds(block_ind,2)]-1);
%         thesetimes = thesetimes - (block_ind - 1)*SR*IBI;
%         
%         fprintf(fid,'%2.0f \n',thesetimes);
%         fclose(fid);
        
        % rename block time file names to agree with neuroscope convention
%         old_block_times_file_name = [datadir 'Block-' num2str(blocks(block_ind)) filesep 'Block-' num2str(blocks(block_ind)) '.res.' num2str(do_groups(group_ind))];
%         new_block_times_file_name = [datadir 'Block-' num2str(blocks(block_ind)) filesep 'Block-' num2str(blocks(block_ind)) '_group' num2str(do_groups(group_ind)) '.res.1'];
%         eval(['! cp ' old_block_times_file_name ' ' new_block_times_file_name ]);

        % The new XML file name should be
        block_XML_file_name =   [datadir  'Block-' num2str(blocks(block_ind)) filesep 'Block-'  num2str(blocks(block_ind)) '-group' num2str(do_groups(group_ind)) '.xml'];      
        eval(['! cp ' xml_file_name ' ' block_XML_file_name ]);
    end
end

return
